sudo: false
jdk:
  - oraclejdk8
language: android
android:
  components:
    - tools
    - android-30
    - platform-tools
    - build-tools-29.0.2
    - extra-android-m2repository
  licenses:
    - android-sdk-license-[0-9a-f]{8}
branches:
  only:
    - master
before_install:
  - mkdir -p "$ANDROID_HOME/licenses"
  - echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"
