sudo: false
jdk:
  - oraclejdk8
language: android
android:
  components:
    - tools
    - platform-tools
    - sys-img-armeabi-v7a-android-15
    - android-23
    - build-tools-23.0.2
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - android-sdk-license-[0-9a-f]{8}
branches:
  only:
    - master
