sudo: false
jdk:
  - oraclejdk8
language: android
android:
  components:
    - tools
    - android-28
    - platform-tools
    - build-tools-28.0.3
    - extra-android-m2repository
  licenses:
    - android-sdk-license-[0-9a-f]{8}
branches:
  only:
    - master
